version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeyzer_pass
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 15432:15432
    environment:
      - PGADMIN_DEFAULT_EMAIL=codeyzer@codeyzer.com
      - PGADMIN_DEFAULT_PASSWORD=789456123
      - PGADMIN_LISTEN_PORT=15432
    volumes:
      - pgadmin4:/var/lib/pgadmin
      - "./pgadmin:/var/lib/pgadmin/storage/codeyzer_codeyzer.com"

  codeyzer-pass:
    build: .
    container_name: codeyzer-pass
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/codeyzer_pass?currentSchema=codeyzer_pass
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin4: