version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeyzer_pass
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 15432:15432
    environment:
      - PGADMIN_DEFAULT_EMAIL=codeyzer@codeyzer.com
      - PGADMIN_DEFAULT_PASSWORD=789456123
      - PGADMIN_LISTEN_PORT=15432
    volumes:
      - pgadmin4:/var/lib/pgadmin
      - "./pgadmin:/var/lib/pgadmin/storage/codeyzer_codeyzer.com"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - mongo:/data/configdb
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 27018:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:mongo@mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=darcula
    depends_on:
      - mongo

volumes:
  postgres:
  pgadmin4:
  mongo: