version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: codeyzer-pass-db
    environment:
      POSTGRES_DB: codeyzer_pass
      POSTGRES_USER: codeyzer
      POSTGRES_PASSWORD: codeyzer123
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    volumes: []
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codeyzer -d codeyzer_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

#volumes:
#  postgres_data:
