server:
  port: ${_PORT:9090}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

  liquibase:
    change-log: classpath:db/changelog/dbchangelog.xml

# Rate limiter global ayarı
rate-limiter:
  enabled: false

  jpa:
    hibernate:
      # Liquibase yöneteceği için Hibernate şema değişikliği yapmasın
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
