server:
  port: ${_PORT:8080}
  ssl:
    enabled: ${_SSL_ENABLED:false}
    key-store: ${_SSL_KEY_STORE}
    key-store-password: ${_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${_SSL_KEY_STORE_TYPE}
    key-alias: ${_SSL_KEY_ALIAS}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${_DATABASE_URL:localhost}:5432/codeyzer_pass?currentSchema=codeyzer_pass
    username: ${_DATABASE_USERNAME:postgres}
    password: ${_DATABASE_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/changelog/dbchangelog.xml

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20